pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    echo "Building Docker image..."

                    // Copy code
                    sh 'cp -r /var/jenkins_workspace/docker-school/* .'

                    // Build image
                    sh '''
                        cd app
                        docker build -t sod-static:${BUILD_NUMBER} .
                    '''

                    echo "Build complete"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo "Testing website..."
                    sh 'docker run -d --name test-container -p 9090:80 sod-static:2'
                    sh 'sleep 5'

                    sh 'docker exec test-container curl localhost'

                    echo "Test complete"
        }
    }
}

    post {
        always {
            sh 'docker stop test-container || true'
            sh 'docker rm test-container || true'
        }
    }
}